version: '3'

services:
  postgres:
    image: postgres:11
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./temp:/var/lib/postgres
