swagger: "2.0"
info:
  title: Geobase
  version: "0.0.1"
basePath: /api
schemes:
  - http

paths:
  /waste/type/{type_id}/location:
    get:
      summary: Получение списка пунктов приема
      description: Определение ближайших точек приема отходов по местоположению
      parameters:
      - name: type_id
        description: id вида отходов 
        in: path
        type: string
        required: true
      - name: latitude
        description: широта
        in: query
        type: number
        format: float
        required: true
      - name: longitude
        description: долгота 
        in: query
        type: number
        format: float
        required: true
      - name: radius
        description: радиус в метрах
        in: query
        type: number
        format: float
        required: false
      produces:
        - application/json
      responses:
        200:
          description: ok
          schema:
            $ref: "#/definitions/MapReference"
        400:
          description: bad request
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json: { "code": 400, "message": {"text": "bad request"}}
        404:
          description: not found
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json: { "code": 404, "message": {"text": "not found"}}
        500:
          description: internal server error
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json: { "code": 500, "message": {"text": "internal server error"}}
      
definitions:
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
      message:
        type: string
      details:
        type: string

  MapReference:
    type: object
    required:
      - url
    properties:
      url:
        type: string
